# ============================================================== #
# Language Configuration Section                                 #
# ============================================================== #

language: "hu" # Supported languages -> hu, en

# ============================================================== #
# Database Configuration Section                                 #
# ============================================================== #

database:
  type: h2 # Supported types -> MYSQL, H2

  # MySQL-specific configuration
  mysql:
    host: localhost
    port: 3306
    database: coma112
    username: root
    password: "" # Enter your MySQL password here (leave empty for no password)
    ssl: false
    certificateverification: false
    poolsize: 10
    lifetime: 1800000

# ============================================================== #
# Item Settings                                                  #
# ============================================================== #

filler-glass-item:
  material: GRAY_STAINED_GLASS_PANE
  name: " "
  lore: [ ]

# ============================================================== #
# Command Settings                                               #
# ============================================================== #

false: "&cFalse"
true: "&aTrue"

aliases:
  - "duty"
  - "dutycore"
  - "admin"

# ============================================================== #
# Duty Settings                                                  #
# ============================================================== #

duty-chat-format: "&e&lDUTY CHAT &8| &e{player} &7> &e{message}"

join-commands:
  every:
    - "say %player% you are a staff I'm sure!"
  admin:
    - "say %player% you are an admin!"
  helper:
    - "say %player% you are a helper!"

leave-commands:
  every:
    - "say %player% you are a staff I'm sure!" # 'every' means it will run not filtering the rank. So nevermind what staff rank you has. it will run.
  admin:
    - "say %player% you are an admin!"
  helper:
    - "say %player% you are a helper!"

join-actionbar:
  enabled: true
  message: "&e{player} &aHas joined to the duty!"
  send-it-to-in-duty: false
  send-it-to-everyone: true # If this is true, it will send it to everyone.

leave-actionbar:
  enabled: true
  message: "&e{player} &cHas left from the duty!"
  send-it-to-in-duty: false # If this is true, it will only send messages to those who are on duty, if false, it will send messages to all people who have dutycore.staff rights.
  send-it-to-everyone: true

# ============================================================== #
# Badge Settings                                                 #
# ============================================================== #

badges:
  copper: "&e&lC" # copper is the actual badge and the string after is a little placeholder which can be helped to identify the badges easily.
  silver: "&f&lS"
  gold: "&6&lG"
  platinum: "&a&lP"
  diamond: "&b&lD"

test-menu:
  title: "Test Menu"
  size: DISPENSER
  update-tick: 20
  items:
    "1":
      material: "STICK"
      amount: 3
      name: "THIS IS A STICK"
      lore:
        - ""
        - "&eLore"
        - "&eds"
      action:
        type:
          - "[LEFT]"
          - "[RIGHT]"
        do:
          - "[MESSAGE] Ez egy üzenet"
          - "[COMMAND] msg %player% Ez is egy üzenet"