# ============================================================== #
# Language Configuration Section                                 #
# ============================================================== #

language: "hu" # Supported languages -> hu, en

# ============================================================== #
# Database Configuration Section                                 #
# ============================================================== #

database:
  type: h2 # Supported types -> MYSQL, H2

  # MySQL-specific configuration
  mysql:
    host: localhost
    port: 3306
    database: coma112
    username: root
    password: "" # Enter your MySQL password here (leave empty for no password)
    ssl: false
    certificateverification: false
    poolsize: 10
    lifetime: 1800000

# ============================================================== #
# Item Settings                                                  #
# ============================================================== #

filler-glass-item:
  material: GRAY_STAINED_GLASS_PANE
  name: " "
  lore: [ ]

# ============================================================== #
# Command Settings                                               #
# ============================================================== #

false: "&cFalse"
true: "&aTrue"

aliases:
  - "duty"
  - "dutycore"
  - "admin"

# ============================================================== #
# Duty Settings                                                  #
# ============================================================== #

duty-chat-format: "&e&lDUTY CHAT &8| &e{player} &7> &e{message}"

join-commands:
  every:
    - "say %player% you are a staff I'm sure!"
  admin:
    - "say %player% you are an admin!"
  helper:
    - "say %player% you are a helper!"

leave-commands:
  every:
    - "say %player% you are a staff I'm sure!" # 'every' means it will run not filtering the rank. So nevermind what staff rank you has. it will run.
  admin:
    - "say %player% you are an admin!"
  helper:
    - "say %player% you are a helper!"

join-actionbar:
  enabled: true
  message: "&e{player} &aSzolgálatba lépett!"
  send-it-to-in-duty: false
  send-it-to-everyone: true # If this is true, it will send it to everyone.

leave-actionbar:
  enabled: true
  message: "&e{player} &cKilépett a szolgálatból!"
  send-it-to-in-duty: false # If this is true, it will only send messages to those who are on duty, if false, it will send messages to all people who have dutycore.staff rights.
  send-it-to-everyone: true

# ============================================================== #
# Badge Settings                                                 #
# ============================================================== #

badges:
  copper: "&e&lC" # copper is the actual badge and the string after is a little placeholder which can be helped to identify the badges easily.
  silver: "&f&lS"
  gold: "&6&lG"
  platinum: "&a&lP"
  diamond: "&b&lD"

# ============================================================== #
# Navigation Menu                                                #
# ============================================================== #

navigation-menu:
  title: "&a&lNAVIGÁCIÓ"
  size: 9
  filler-glass: true

  staff-menu-item:
    amount: 1
    material: RED_CANDLE
    name: "&a&lSTAFFOK"
    slot: 3

  sanction-menu-item:
    amount: 1
    material: ORANGE_CANDLE
    name: "&a&lSZANKCIONÁLÁS"
    slot: 5

# ============================================================== #
# Staff Menu                                                     #
# ============================================================== #

staff-menu:
  title: "&a&lSTAFFOK"
  size: 54
  filler-glass: true

  staff-item:
    lore:
      - "TODO infok"

# ============================================================== #
# Sanction Menu                                                  #
# ============================================================== #

sanction-menu:
  title: "&a&lSZANKCIONÁLÁS"
  size: 0
  type: "DISPENSER"
  filler-glass: true #warn, ban, mute, kick

  warn-item:
    amount: 1
    material: LIGHT_GRAY_CANDLE
    name: "&7WARN {player}"
    slot: 0
  kick-item:
    amount: 1
    material: YELLOW_CANDLE
    name: "&eKICK {player}"
    slot: 2
  mute-item:
    amount: 1
    material: ORANGE_CANDLE
    name: "&6MUTE {player}"
    slot: 6
  ban-item:
    amount: 1
    material: RED_CANDLE
    name: "&cBAN {player}"
    slot: 8