# ============================================================== #
# Language Configuration Section                                 #
# ============================================================== #

language: "hu" # Supported languages -> hu, en

# ============================================================== #
# Command Settings                                               #
# ============================================================== #

false: "&cFalse"
true: "&aTrue"

aliases:
  - "duty"
  - "dutycore"
  - "admin"