name: DutyCore
version: '1.0.0'
main: net.solostudio.dutycore.DutyCore
api-version: '1.20'
authors: [ Solo Studio ]
folia-supported: true
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
loadbefore: [LuckPerms, PlaceholderAPI]